### PR TITLE
Str2I64() octal prefix 0o

### PR DESCRIPTION
**Pull request by mknos**
* Comment at top of function hints that 0o18 is treated as an octal number but it is not
* Adding the appropriate switch-case makes it work by adjusting radix
* Update comment: this function is more like strtol() because it returns a signed result
* This function doesn't behave like strtol() because "0" prefix can't be used for octal, e.g. "0777" (maybe it could be supported in future)

### CODE REVIEW

**Comment by mknos** [comment]
Sorry, it looks like gitlab auto-converted the file to utf8 but I didn't intend that extra change, and the build might break depending on utf8 support.

**Comment by GutPuncher** [comment]
> Sorry, it looks like gitlab auto-converted the file to utf8 but I didn't intend that extra change, and the build might break depending on utf8 support.

Thanks, the code change looks good, great catch on the missing radix! To fix erroneous utf8 conversions, you could run:
`git checkout -p master -- src/Kernel/StrScan.ZC`
in your feature branch to  selectively checkout just the sections of the file you want to 'undo' the changes to for the PR.

**Comment by mknos** [comment]
OK, I think the file is back to normal now.

**Comment by GutPuncher** [comment]
Didn't catch the update on this until now, thanks for fixing the symbol issue in the commit!

**Pull request merged**
