### PR TITLE
Dont copy hidden files/folders to VM

### PR DESCRIPTION
**Pull request by y4my4my4m**
I've modified the sync script to ignore all `.*` files/folders.

The goal with this is to be able to have sub gits (not submodules) without copying the .git folders to the VM.

For example, with this I am able to clone the https://github.com/y4my4my4m/ZealAMP repository to my src/Home folder and work on it separately without having the .git folder and it's .gitignore file within the folder in the VM.

### CODE REVIEW

**Comment by xslendix** [comment]
Not everyone has `rsync` installed on their system, you should use `find` instead and iterate through each individual file.

**Comment by xslendix** [comment]
> @xslendix they almost do no?

No.

> Only ones I can think that don't are minimalist distros made for containization like Alpine linux.
> Maybe Arch base install doens't have it, but it doesn't have anything at all, which in this case falls back on the user imo.

build.sh should work for any Linux distros.

> I didn't use `find` because it would be much slower, am I mistaken?

Yes but not considerably.

> Let me know what the find command would look like for that purpose.

find -type f -not -path '*/.*'

**Comment by y4my4my4m** [comment]
@xslendix the command is fairly convoluted but that's the only way i was able to make it work to ignore both dotfolders and dotfiles.

Here's what I've tested


- /.myhiddenfile
- /.myhiddenfolder
   - /myfile.TXT
   - /.mysubhiddenfile
- /mynormalfile.TXT
- /mynormalfolder
  - /.mysubhiddenfileinnormalfolder
  - /mynormalfileinnormalfolder.TXT

the behaviour was as expected, everything dot would get ignored (even normal files in hidden folders) and normal files/folders would get properly copied over

**Comment by GutPuncher** [comment]
> The goal with this is to be able to have sub gits (not submodules) without copying the .git folders to the VM.

If that is the goal, this change should only filter out .git and .gitignore, rather than filtering out `.` prefixed filenames. Zeal handles dotfiles/dotfolders as if they aren't hidden and they are still valid as names (a developer is free to have files in their project starting with `.`, a user is free to unzip files/folders into `src/` to be viewed from within Zeal that are within a file/directory prefixed with `.`), so excluding all `.*` pattern names from sync is a bit extreme if the intended goal was just to not sync specific git-related hidden files within `src/`.

**Comment by y4my4my4m** [comment]
@GutPuncher 
that is something I hadn't considered.
I've removed the .gitignore and I've now changed the command to accept an argument `--ignore-dots` or `--dots`
Meaning that:
`sync.sh vm` will function as it previously did
and
`sync.sh vm --ignore-dots` will use the new "find" and filter out dotfiles/dotfolders

**Pull request merged**
