### PR TITLE
ConversionScript update

### PR DESCRIPTION
**Pull request by y4my4my4m**
I found some missing conversion and I've added them.
I'm still fiddling with stuff so I'll change it from draft to a real PR when I'm done.

### CODE REVIEW

**Comment by y4my4my4m** [comment]
This is good enough for now, there's still a lot more to find and add, but I've had minimal success with these additions for a bunch of Alec Murphy's programs

**Review by xslendix — APPROVED** [review]
LGTM but I don't think a comment for the Adam one is needed

**Comment by y4my4my4m** [comment]
> LGTM but I don't think a comment for the Adam one is needed

I just didn't want people to question the open parenthesis

**Review by GutPuncher — APPROVED** [review]
Good stuff

**Pull request merged**
